---
- hosts: dev
  become: true
  tasks:
    - name: install python pip
      yum: 
        name: python-pip
        state: present
    - name: install docker-py python ansible_os_family
      pip:
        name: docker-py
        state: present
    - name: start the container
      docker-container:
        name: fairozapp
        image: "fairoz/fairozapp:${DOCKER_TAG}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
          
